### ISSUE TITLE
Errors in the documentation of parseRel?

### ISSUE THREAD

**Issue by poscat0x04** [hasufell/hpath#36]
According to the [documentation](https://hackage.haskell.org/package/hpath-0.11.0/docs/HPath.html#v:parseRel) of parseRel:

> Note that filepath may contain any number of ./ but may not consist solely of ./.

but apparently `isJust $ parseRel "./"` evaluates to `True`. Am I missing something?

**Comment by hasufell** [comment]
I'd say that's a bug. It's supposed to return `Nothing`.

However, looking at other path libraries it seems we could permit this, so:

```
parseRel "." -> Just "."
parseRel "././././." -> Just "."
parseRel "./..." -> Just "..."
parseRel ".." -> Nothing
```

I'm not entirely sure what the implications are for the rest of the code. But we can reasonably normalize it without IO, which isn't possible for `..`, which will still needs to be rejected.

**Comment by hasufell** [comment]
ping @poscat0x04 ideas?
