### ISSUE TITLE
stripping a relative directory from itself should yield ./

### ISSUE THREAD

**Issue by poscat0x04** [hasufell/hpath#37]
not sure why this is not the case

**Comment by hasufell** [comment]
Yes, the doctests include this case: https://hackage.haskell.org/package/hpath-0.11.0/docs/HPath.html#v:stripDir

It's supposed to return `Nothing`. If we add `.` to the list of valid relative dirs wrt https://github.com/hasufell/hpath/issues/36, then we could do differently.

**Comment by hasufell** [comment]
ping
